name: Terraform Workflow

on:
  push:
    branches: ["iaac/config"]
  pull_request:
    branches: ["iaac/config"]
  
jobs:
  terraform-validate-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform validate
        run: terraform validate
      
      - name: Terraform plan
        run: terraform plan
