name: Terraform Workflow

on:
  push:
    branches:
      - iaac/config
  pull_request:
    branches:
      - iaac/config
  
jobs:
  terraform-validate-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set up AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          if [ -n "${{ secrets.AWS_SESSION_TOKEN }}" ]; then
            echo "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials
          fi
          aws configure set region us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform validate
        run: terraform validate
      
      - name: Terraform plan
        run: terraform plan
