name: Terraform Workflow

on:
  push:
    branches:
      - iaac/config
  pull_request:
    branches:
      - iaac/config
  
jobs:
  terraform-validate-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set up SSH KEY FOR AWS
        run: |
          echo "${{ secrets.SSH_PUB_KEY }}" | base64 -d > /id_rsa.pub
          chmod 600 /id_rsa

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          if [ -n "${{ secrets.AWS_SESSION_TOKEN }}" ]; then
            aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          fi
          aws configure set region us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform validate
        run: terraform validate
      
      - name: Terraform plan
        run: terraform plan
